export const ContractText = `VIVIMUS PECUNIA EMPLOYMENT CONTRACT:

By accepting this agreement, you acknowledge and accept the terms set forth by Vivimus Pecunia. This contract formalizes your role within the organization, establishes your duties, and outlines the benefits and conditions attached to your employment. Read carefully, because ignorance is rarely accepted as an excuse.

POSITION: Upon signing, you are recognized as a member of the Vivimus Pecunia workforce. While your title might sound grandiose, please do not let it give you illusions of grandeur. Titles are placeholders and subject to change, especially during quarterly reviews, where they often devolve into more accurate depictions of your performance. Your duties are vast and deliberately vague, but we assure you they will encompass far more than what you initially anticipated. Flexibility is expected, though you may often hear it referred to as "team spirit" or "initiative."

WORKING HOURS: Working hours are theoretically defined as nine to five. Theoretically. In practice, you may discover that work tends to spill over, much like our Friday drinks, into evenings and weekends. Overtime is rewarded with a gentle nod of acknowledgment from your manager and the occasional “good job.” If you're lucky, it might also result in one fewer passive-aggressive email the next morning.

COMPENSATION: You will be compensated in a currency we currently refer to as "money", but our fiscal team is exploring alternative payment methods that better align with our forward-thinking approach, such as loyalty points, redeemable smiles, or employee-of-the-month badges. Your salary will be sufficient, at least in comparison to an intern's. Raises are tied to your ability to endure multiple fiscal cycles without questioning why the company-wide bonuses somehow never trickle down to your department.

BENEFITS: Vivimus Pecunia offers a range of benefits aimed at improving your work-life balance, assuming such a balance still exists by the time you are done reading this. These include, but are not limited to, health coverage (subject to approval, naturally), occasional access to the communal snack drawer, and a potential "well-being day," though the latter tends to align suspiciously with national holidays. The health plan ensures that we do the bare minimum to keep you functioning, but rest assured, therapy is included—provided it is work-related stress and directly improves productivity.

NON-DISCLOSURE: During your employment, you will be privy to confidential information, much of which you won't even understand but must nonetheless protect with your life (and perhaps your job). Any breach of this clause will result in swift and severe consequences, ranging from a formal warning to a demotion to the office next to the janitor's closet. The severity of the breach will dictate the size of the broom.

TERMINATION: Should you choose—or be persuaded—to leave the company, you are expected to give notice, though the length of said notice may vary depending on how much we need you that particular week. On termination, you will be required to return all company property, including the office pen you thought no one noticed you took, and access to the company Slack channel will be revoked immediately, unless you stay logged in by accident, in which case we trust you'll stop responding to work queries. Severance packages will be discussed at the discretion of senior management, though it's best not to expect much beyond a polite farewell and maybe a piece of leftover cake if someone's birthday happens to fall on your final day.

DISCLAIMER: Vivimus Pecunia is not responsible for any unrealistic expectations formed during your employment. This contract supersedes any casual assurances made by colleagues or management, especially when drinks are involved. Should disputes arise, they will be resolved swiftly using our usual arbitration methods—namely, forgetting about it altogether or deferring the problem to someone else.`